### ISSUE TITLE
Failed to implement get_query_var()

### ISSUE THREAD

**Issue by wdj-ac** [DevinVinson/WordPress-Plugin-Boilerplate#421]
Hi folks,

sorry for this (maybe) stupid question, but i am not able to call the wordpress function get_query_var(). Everytime I activate my Plugin  I get this error:

`Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/html/wp-includes/query.php:28 Stack trace: #0 /var/www/html/wp-content/plugins/touchpoints/includes/class-touchpoints.php(255): get_query_var('origin') #1 /var/www/html/wp-content/plugins/touchpoints/includes/class-touchpoints.php(82): Touchpoints->get_query_var_origin('origin') #2 /var/www/html/wp-content/plugins/touchpoints/touchpoints.php(71): Touchpoints->__construct() #3 /var/www/html/wp-content/plugins/touchpoints/touchpoints.php(75): run_touchpoints() #4 /var/www/html/wp-settings.php(304): include_once('/var/www/html/w...') #5 /var/www/html/wp-config.php(105): require_once('/var/www/html/w...') #6 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #7 /var/www/html/wp-admin/admin.php(31): require_once('/var/www/html/w...') #8 /var/www/html/wp-admin/plugins.php(10): require_once('/var/www/html/w...') #9 {main} thrown in /var/www/html/wp-includes/query.php on line 28`

I added some functions and actions in class-pluginname.php:
```
<?php

/**
 * The file that defines the core plugin class
 *
 * A class definition that includes attributes and functions used across both the
 * public-facing side of the site and the admin area.
 *
 * @link       http://neusite.de
 * @since      1.0.0
 *
 * @package    Touchpoints
 * @subpackage Touchpoints/includes
 */

/**
 * The core plugin class.
 *
 * This is used to define internationalization, admin-specific hooks, and
 * public-facing site hooks.
 *
 * Also maintains the unique identifier of this plugin as well as the current
 * version of the plugin.
 *
 * @since      1.0.0
 * @package    Touchpoints
 * @subpackage Touchpoints/includes
 * @author     Pascal Jordin <p.jordin@neusite.de>
 */
class Touchpoints {

    //global $wp_query;

	/**
	 * The loader that's responsible for maintaining and registering all hooks that power
	 * the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      Touchpoints_Loader    $loader    Maintains and registers all hooks for the plugin.
	 */
	protected $loader;

	/**
	 * The unique identifier of this plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      string    $plugin_name    The string used to uniquely identify this plugin.
	 */
	protected $plugin_name;

	/**
	 * The current version of the plugin.
	 *
	 * @since    1.0.0
	 * @access   protected
	 * @var      string    $version    The current version of the plugin.
	 */
	protected $version;

    /**
     * The Contents of the query variable.
     *
     * @since    1.0.0
     * @access   private
     * @var      string    $origin    The origin of a visitor
     */
    private $origin;

	/**
	 * Define the core functionality of the plugin.
	 *
	 * Set the plugin name and the plugin version that can be used throughout the plugin.
	 * Load the dependencies, define the locale, and set the hooks for the admin area and
	 * the public-facing side of the site.
	 *
	 * @since    1.0.0
	 */
	public function __construct() {

		$this->plugin_name = 'touchpoints';
		$this->version = '1.0.0';
        $this->origin = $this->get_query_var_origin();

		$this->load_dependencies();
		$this->set_locale();
		$this->define_admin_hooks();
		$this->define_public_hooks();

	}

	/**
	 * Load the required dependencies for this plugin.
	 *
	 * Include the following files that make up the plugin:
	 *
	 * - Touchpoints_Loader. Orchestrates the hooks of the plugin.
	 * - Touchpoints_i18n. Defines internationalization functionality.
	 * - Touchpoints_Admin. Defines all hooks for the admin area.
	 * - Touchpoints_Public. Defines all hooks for the public side of the site.
	 *
	 * Create an instance of the loader which will be used to register the hooks
	 * with WordPress.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function load_dependencies() {

		/**
		 * The class responsible for orchestrating the actions and filters of the
		 * core plugin.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'includes/class-touchpoints-loader.php';

		/**
		 * The class responsible for defining internationalization functionality
		 * of the plugin.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'includes/class-touchpoints-i18n.php';

		/**
		 * The class responsible for defining all actions that occur in the admin area.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/class-touchpoints-admin.php';

		/**
		 * The class responsible for defining all actions that occur in the public-facing
		 * side of the site.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) . 'public/class-touchpoints-public.php';

		$this->loader = new Touchpoints_Loader();

	}

	/**
	 * Define the locale for this plugin for internationalization.
	 *
	 * Uses the Touchpoints_i18n class in order to set the domain and to register the hook
	 * with WordPress.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function set_locale() {

		$plugin_i18n = new Touchpoints_i18n();

		$this->loader->add_action( 'plugins_loaded', $plugin_i18n, 'load_plugin_textdomain' );

	}

	/**
	 * Register all of the hooks related to the admin area functionality
	 * of the plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function define_admin_hooks() {

		$plugin_admin = new Touchpoints_Admin( $this->get_plugin_name(), $this->get_version(), $this->get_origin() );

		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );
		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );

	}

	/**
	 * Register all of the hooks related to the public-facing functionality
	 * of the plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function define_public_hooks() {

		$plugin_public = new Touchpoints_Public( $this->get_plugin_name(), $this->get_version(), $this->get_origin() );

        $this->loader->add_filter('query_vars', $plugin_public, 'add_query_vars_filter', 1 , 1);

		$this->loader->add_action( 'wp_enqueue_scripts', $plugin_public, 'enqueue_styles' );
		$this->loader->add_action( 'wp_enqueue_scripts', $plugin_public, 'enqueue_scripts' );
        $this->loader->add_action( 'wp_loaded', $plugin_public, 'touchpoint_check', 11, 1 );
        $this->loader->add_action( 'wp_loaded', $plugin_public, 'get_query_var_origin');
	}

	/**
	 * Run the loader to execute all of the hooks with WordPress.
	 *
	 * @since    1.0.0
	 */
	public function run() {

		$this->loader->run();
	}

	/**
	 * The name of the plugin used to uniquely identify it within the context of
	 * WordPress and to define internationalization functionality.
	 *
	 * @since     1.0.0
	 * @return    string    The name of the plugin.
	 */
	public function get_plugin_name() {
		return $this->plugin_name;
	}

	/**
	 * The reference to the class that orchestrates the hooks with the plugin.
	 *
	 * @since     1.0.0
	 * @return    Touchpoints_Loader    Orchestrates the hooks of the plugin.
	 */
	public function get_loader() {
		return $this->loader;
	}

	/**
	 * Retrieve the version number of the plugin.
	 *
	 * @since     1.0.0
	 * @return    string    The version number of the plugin.
	 */
	public function get_version() {
		return $this->version;
	}

    /**
     * TODO
     * @param $vars
     * @return array
     */
    function add_query_vars_filter( $vars ){
        $vars[] = "origin";
        return $vars;
    }

    /**
     * The origin of a visitor.
     *
     * @since     1.0.0
     * @return    string    The origin.
     */
    public function get_origin() {
        return $this->origin;
    }

    /**
     * The origin of a visitor.
     *
     * @since     1.0.0
     * @return    string    The origin.
     */
    public function get_query_var_origin() {
        return get_query_var('origin');
    }
}
```

How to be able to call a wp_query function in this plugin boilerplate?
Thanks for Help!

**Comment by badah** [comment]
You are trying to pass this `get_query_var_origin` method as an instance of Touchpoints_Public class to the wp_loaded hook:
`$this->loader->add_action( 'wp_loaded', $plugin_public, 'get_query_var_origin');`

This method is probably not present in `$plugin_public` object class, which is Touchpoints_Public. So you should try to move it to there.
